// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/rodericusifo/football-club-profile/src/core/v1/area/controller"
	"github.com/rodericusifo/football-club-profile/src/core/v1/area/resource"
	"github.com/rodericusifo/football-club-profile/src/core/v1/area/service"
	"github.com/rodericusifo/football-club-profile/src/core/v1/team/controller"
	"github.com/rodericusifo/football-club-profile/src/core/v1/team/resource"
	"github.com/rodericusifo/football-club-profile/src/core/v1/team/service"
	"github.com/rodericusifo/football-club-profile/src/core/v1/user/controller"
	"github.com/rodericusifo/football-club-profile/src/core/v1/user/resource"
	"github.com/rodericusifo/football-club-profile/src/core/v1/user/service"
)

// Injectors from wire.go:

func UserControllerV1() *controller_user_v1.UserController {
	iUserResource := resource_user_v1.InitUserResource()
	iUserService := service_user_v1.InitUserService(iUserResource)
	userController := controller_user_v1.InitUserController(iUserService)
	return userController
}

func AreaControllerV1() *controller_area_v1.AreaController {
	iAreaResource := resource_area_v1.InitAreaResource()
	iAreaService := service_area_v1.InitAreaService(iAreaResource)
	areaController := controller_area_v1.InitAreaController(iAreaService)
	return areaController
}

func TeamControllerV1() *controller_team_v1.TeamController {
	iTeamResource := resource_team_v1.InitTeamResource()
	iTeamService := service_team_v1.InitTeamService(iTeamResource)
	teamController := controller_team_v1.InitTeamController(iTeamService)
	return teamController
}
